# Generated by Django 5.1.6 on 2025-03-18 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Izohlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=200)),
                ('familiya', models.CharField(max_length=200)),
                ('elektron_pochta', models.EmailField(max_length=200)),
                ('tel_raqam', models.IntegerField(default=999)),
                ('txt', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Izohlar',
                'db_table': 'Izohlar',
            },
        ),
        migrations.CreateModel(
            name='Loyihalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soxasi', models.CharField(max_length=200, verbose_name='soxasi')),
                ('nomi', models.CharField(max_length=200, verbose_name='yangliklar')),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('izoh', models.TextField(max_length=2000, verbose_name='izoh')),
            ],
            options={
                'verbose_name': 'Loyihalar',
                'db_table': 'Loyihalar',
            },
        ),
        migrations.CreateModel(
            name='Registr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=200)),
                ('familiya', models.CharField(max_length=200)),
                ('elektron_pochta1', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default=999)),
            ],
            options={
                'db_table': 'Registr',
            },
        ),
        migrations.CreateModel(
            name='Salohiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daraja', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'salohiyat',
            },
        ),
        migrations.CreateModel(
            name='Tadbirlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='yangliklar')),
                ('video', models.FileField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Tadbirlar',
                'db_table': 'Tadbirlar',
            },
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='FISH')),
                ('yoshi', models.IntegerField(default=1)),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('izoh', models.TextField(max_length=2000, verbose_name='izoh')),
            ],
            options={
                'db_table': 'Talaba',
            },
        ),
        migrations.CreateModel(
            name='Tugarak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('subjects', models.CharField(max_length=200, verbose_name='nomi')),
                ('body_small', models.TextField()),
                ('body', models.TextField()),
                ('muallimi', models.CharField(max_length=200)),
                ('muallim_name', models.CharField(max_length=200)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "To'garak",
                'db_table': "To'garak",
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='yangliklar')),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('xolat', models.CharField(choices=[('QORALAMA', 'QORALAMA'), ('CHOP_ETISH', 'CHOP_ETISH')], max_length=120, verbose_name='xolati')),
                ('slug', models.SlugField(max_length=200)),
                ('body', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'df'), ('PUBLISHED', 'pd')], default='DRAFT', max_length=10)),
                ('sana', models.DateTimeField(auto_now_add=True, null=True, verbose_name='sana')),
                ('izoh', models.TextField(max_length=2000, verbose_name='izoh')),
                ('xolati', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='baza.category')),
            ],
            options={
                'verbose_name': 'News',
                'db_table': 'News',
            },
        ),
        migrations.CreateModel(
            name='Muallim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasmi', models.ImageField(upload_to='images/')),
                ('ismi', models.CharField(max_length=200)),
                ('familiyasi', models.CharField(max_length=200)),
                ('yoshi', models.IntegerField(default=1)),
                ('mutaxassisligi', models.CharField(max_length=200)),
                ('yuklangan_sanasi', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=200)),
                ('body', models.TextField()),
                ('body_small', models.TextField()),
                ('ilmiy_salohiyati', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='baza.salohiyat')),
            ],
            options={
                'verbose_name': 'Muallim',
                'db_table': 'Muallim',
            },
        ),
    ]
